In [1]:
	import numpy as np
	import pandas as pd
	
	df = pd.read_csv('spam.csv', encoding='latin-1') # specifying encoding is necessary because the data does not use UTF-8
	
	df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [2]:
	# Drop the last 3 columns using iloc
	df = df.drop(df.iloc[:,2:], axis=1)
	
	# Check the data
	df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
# Check the number of instances per class
print(df['v1'].value_counts())
print('\n')

# Check for completeness of data
print(df.info())
print('\n')

# Check descriptive statistics
print(df.describe())

v1
ham     4825
spam     747
Name: count, dtype: int64


<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   v1      5572 non-null   str
 1   v2      5572 non-null   str
dtypes: str(2)
memory usage: 541.4 KB
None


          v1                      v2
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [10]:
	# Data for labels
	new_labels = {
	    'spam': 1,
	    'ham': 0
	}
	
	# Encode labels
	df['v1'] = df['v1'].map(new_labels)
	
	# Check the data
	df.head()

   v1                                                 v2
0   0  Go until jurong point, crazy.. Available only ...
1   0                      Ok lar... Joking wif u oni...
2   1  Free entry in 2 a wkly comp to win FA Cup fina...
3   0  U dun say so early hor... U c already then say...
4   0  Nah I don't think he goes to usf, he lives aro...

In [18]:
X = df['v2'].values
y = df['Labels'].values

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Split training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

# Initialize CountVectorizer
bow = CountVectorizer()

In [29]:
print(len(bow.get_feature_names_out()))
print(f'Data dimensions: {X_train.shape}')

7727
Data dimensions: (4457, 7727)

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
	from sklearn.naive_bayes import MultinomialNB
	from sklearn.metrics import accuracy_score
	
	# Initialize MultinomialNB
	mnb = MultinomialNB()
	
	# Fit the model
	mnb.fit(X_train, y_train)
	
	# Predict on the training data
	y_pred_train = mnb.predict(X_train)
	
	# Evaluate training accuracy
	acc_train = accuracy_score(y_train, y_pred_train)
	
	# Predict on the training data
	y_pred_test = mnb.predict(X_test)
	
	# Evaluate training accuracy
	acc_test = accuracy_score(y_test, y_pred_test)
	
	# Print evaluation results
	print(f'Training data accuracy: {acc_train}')
	print(f'Test data accuracy: {acc_test}')

Training data accuracy: 0.9946152120260264
Test data accuracy: 0.9775784753363229

In [41]:
y_pred_train = mnb.predict(X_train)
y_pred_test = mnb.predict(X_test)